version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 2
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    ignore:
      # ignore patch updates. they are frequently updated.
      - dependency-name: boto3
        versions:
          - "<1.17.0"
      - dependency-name: botocore
        versions:
          - "<1.20.0"
