name: 'actions-cfn-lint'
description: 'cfn-lint with reviewdog'
author: 'Ichinose Shogo'
inputs:
  github_token:
    description: 'set ${{ secrets.GITHUB_TOKEN }}'
    required: true
outputs: {}
runs:
  using: 'docker'
  image: 'Dockerfile'
