name: build Docker Image

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - 'v*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show Version
        run: |
          echo "::set-env name=VERSION::$(cat VERSION)"
      - name: Build the Docker image
        run: docker build -t ${{ github.repository }}:"$VERSION" .
      - name: Publish
        run: |
          printenv PASSWORD | docker login -u "$USERNAME" --password-stdin
          docker push ${{ github.repository }}:"$VERSION"
          docker logout
        env:
          USERNAME: ${{ secrets.username }}
          PASSWORD: ${{ secrets.password }}
