name: build Docker Image

on: pull_request

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: minimum example
        uses: ./

      - name: with args
        uses: ./
        with:
          args: testdata/template.yaml
