name: build Docker Image

on:
  pull_request:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t ${{ github.repository }}:latest .
      - name: Publish
        run: |
          printenv PASSWORD | docker login -u "$USERNAME" --password-stdin
          docker push ${{ github.repository }}:latest
          docker logout
