name: build Docker Image

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: minimum example
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: with args
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        args: testdata/template.yaml
