name: test

on: pull_request

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: minimum example
        uses: ./

      - name: with args
        uses: ./
        with:
          tool_name: cfn-lint with args
          args: testdata/template.yaml
