name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show Version
        run: |
          echo "VERSION=$(cat VERSION)" >> "$GITHUB_ENV"
      - name: Build the Docker image
        run: docker build -t ${{ github.repository }}:"$VERSION" .

      - name: minimum example
        uses: ./
        with:
          level: warning

      - name: with args
        uses: ./
        with:
          level: warning
          tool_name: cfn-lint with args
          cfn_lint_args: testdata/template.yaml
