name: update
on:
  schedule:
    - cron: "25 20 * * *"
  workflow_dispatch:

jobs:
  requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: update requirements.txt
        id: update
        run: |
          mv requirements.txt requirements.old.txt
          make requirements

          # boto3 and botocore are updated very often, so ignore them
          diff <(cat requirements.old.txt | grep -v -E 'boto(3|core)') \
            <(cat requirements.txt | grep -v -E 'boto(3|core)') && true
          echo "::set-output name=result::$?"
          rm requirements.old.txt

      - name: commit
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        if: steps.update.outputs.result == '1'
        run: |
          branch=update-requirements-$(date +"%Y-%m-%d-%H-%M-%S")
          git config --global user.name "Ichinose Shogo"
          git config --global user.email shogo82148@gmail.com
          git switch -c "$branch"
          git add .
          git commit -m "Update requirements.txt $(date +"%Y-%m-%d %H:%M:%S")" || exit 0
          git push -u origin $branch
          curl -H "Authorization: token $TOKEN" \
            -d "$(jq --arg branch $branch -n '{ "title": "Auto Update", "base": "main", "head": $branch }')" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls"
